import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/Navbar";
import { MessageIcon, TaskIcon } from "@/components/icons";
import { Menu } from "@/components/Menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="relative flex w-full">
          <div className="lg:block w-[285px] h-screen border-r border-r-gray6"></div>
          <div className="flex-1 h-screen">
            <Navbar />
            <div className="absolute bottom-20 right-0 w-1/3 h-2/3 p-5">
              <div className="flex bg-white p-5 h-full rounded-md">
                {children}
              </div>
            </div>
            <Menu />
          </div>
        </main>
      </body>
    </html>
  );
}
